# Generated by Django 4.1 on 2023-04-30 13:47

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, "Rating must be at least 1 star."
                            ),
                            django.core.validators.MaxLengthValidator(
                                5, "Rating cannot be more than 5 stars."
                            ),
                        ],
                        verbose_name="Stars",
                    ),
                ),
                ("review", models.TextField()),
                ("spoliers", models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
