# Generated by Django 4.1 on 2023-04-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="spoliers",
            new_name="spoilers",
        ),
    ]
